name: lumo_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shadcn_ui: ^0.31.8
  go_router: ^16.2.4
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  retrofit: ^4.7.2
  logger: ^2.6.1
  json_annotation: ^4.9.0
  injectable: ^2.5.1
  flutter_dotenv: ^6.0.0
  lucide_icons: ^0.257.0
  flutter_svg: ^2.2.1
  equatable: ^2.0.5
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^10.0.5
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.14.2
  freezed: ^3.2.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
